ARG BUILD_FROM
FROM $BUILD_FROM

ENV LANG C.UTF-8

ADD package.json /

RUN apk add --no-cache nodejs-npm jq && \
npm install

# Copy data for add-on
COPY run.sh /
COPY index.js /
COPY config.js /
RUN chmod a+x /index.js

CMD [ "/index.js" ]


# Alternative executing run.sh:
#COPY run.sh /
#RUN chmod a+x /run.sh

#CMD [ "/run.sh" ]
