ARG BUILD_FROM
FROM $BUILD_FROM

ENV LANG C.UTF-8

ADD package.json /

RUN apk add --no-cache nodejs-npm jq && \
npm install

# Expose all ports used by the eNet Mobile Gate API 
EXPOSE 2906
EXPOSE 3112
EXPOSE 9050

# Copy data for add-on
COPY run.sh /
COPY index.js /
COPY config.js /

# Directly run index.js
RUN chmod a+x /index.js
CMD [ "/index.js" ]

# Alternative executing run.sh:
#RUN chmod a+x /run.sh
#CMD [ "/run.sh" ]
